#ifndef GUICOMMONFUNCTIONLIB_GLOBAL_H
#define GUICOMMONFUNCTIONLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GUICOMMFUNCLIB_LIBRARY)
    #define GUICOMMFUNCLIB_EXPORT Q_DECL_EXPORT
#else
    #define GUICOMMFUNCLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // GUICOMMFUNCLIB_GLOBAL_H
